### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by soneill93237** [iteague/CafeNervosa#1]
what can i do with this software?  is it true that i can scrape frasier?

**Comment by iteague** [comment]
Yes right now it goes to urls on www.frasieronline.co.uk and grabs the html title of each season's page. I'm going to add to it soon to make it scrape the data for every episode and put it into a mySQL database.

**Comment by iteague** [comment]
to run it you have to download scrapy and run from the top directory of CafeNervosa: 

scrapy crawl episodes -o episodes.json

that will put the data it scraped from the website in a file called episodes.json

**Comment by soneill93237** [comment]
this is working very well for me.  thank you.

**Comment by iteague** [comment]
you're welcome, or as Frasier would say, "Six months ago, I was living in Boston. My wife had left me, which was very painful."
